"""Khởi tạo các bảng

Revision ID: d2b239dfb970
Revises: 
Create Date: 2022-11-13 20:36:21.492173

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision = "d2b239dfb970"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("img", sa.String(), nullable=False),
        sa.Column("describe", sa.Text(), nullable=True),
        sa.Column("director", sa.String(length=50), nullable=False),
        sa.Column("actor", sa.Text(), nullable=False),
        sa.Column("genre", sa.Text(), nullable=False),
        sa.Column("release_date", sa.String(length=20), nullable=False),
        sa.Column("running_time", sa.String(length=50), nullable=False),
        sa.Column("language", sa.Text(), nullable=True),
        sa.Column("rated", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "suppliers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("img_price_ticket", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fullname", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("phone_number", sa.String(length=10), nullable=False),
        sa.Column("gender", sa.String(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone_number"),
    )
    op.create_table(
        "cinemas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_supplier", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("hotline", sa.String(length=20), nullable=True),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT", from_text="ST_GeomFromEWKT", name="geometry"
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["id_supplier"],
            ["suppliers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # op.create_index('idx_cinemas_geom', 'cinemas', ['geom'], unique=False, postgresql_using='gist')
    op.create_table(
        "evaluates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_user", sa.Integer(), nullable=False),
        sa.Column("id_cinema", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("star_rated", sa.Integer(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_cinema"],
            ["cinemas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_user"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "movie_showtimes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_cinema", sa.Integer(), nullable=False),
        sa.Column("id_movie", sa.Integer(), nullable=False),
        sa.Column("screening_date", sa.String(length=50), nullable=False),
        sa.Column("time_start", sa.String(length=20), nullable=True),
        sa.Column("seats", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_cinema"],
            ["cinemas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_movie"],
            ["movies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movie_showtimes")
    op.drop_table("evaluates")
    op.drop_index("idx_cinemas_geom", table_name="cinemas", postgresql_using="gist")
    op.drop_table("cinemas")
    op.drop_table("users")
    op.drop_table("suppliers")
    op.drop_table("movies")
    # ### end Alembic commands ###
